"use client"

import React from "react"
import { motion } from "framer-motion"
import { FileText, Download, Share2, Printer } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Navbar from "@/components/layout/Navbar"

export default function ReportDetailPage({ params }: { params: { id: string } }) {
  return (
    <main className="min-h-screen pt-20 pb-12">
      <Navbar />
      <div className="section-padding max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center justify-between">
            <div>
              <span className="label-gold mb-2 block">Report #{params.id}</span>
              <h1 className="heading-section">Birth Chart Analysis</h1>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="sm">
                <Share2 className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="sm">
                <Printer className="h-4 w-4" />
              </Button>
              <Button variant="secondary" size="sm">
                <Download className="h-4 w-4 mr-2" />
                PDF
              </Button>
            </div>
          </div>
        </motion.div>

        <Card className="glass-panel">
          <CardContent className="p-8">
            <div className="text-center mb-8 pb-8 border-b border-gold-antique/10">
              <h2 className="font-serif text-2xl text-moon-white mb-2">AstraVeda 3D</h2>
              <p className="text-gold-antique text-sm">Personalized Birth Chart Report</p>
              <p className="text-xs text-lavender/40 mt-2">Generated on 20 August 2026</p>
            </div>

            <div className="space-y-6">
              <section>
                <h3 className="font-serif text-lg text-moon-white mb-3">Birth Details</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-lavender/50">Name:</span>
                    <span className="text-moon-white ml-2">Rahul Sharma</span>
                  </div>
                  <div>
                    <span className="text-lavender/50">Date:</span>
                    <span className="text-moon-white ml-2">15 March 1995</span>
                  </div>
                  <div>
                    <span className="text-lavender/50">Time:</span>
                    <span className="text-moon-white ml-2">08:30 AM</span>
                  </div>
                  <div>
                    <span className="text-lavender/50">Place:</span>
                    <span className="text-moon-white ml-2">New Delhi, India</span>
                  </div>
                </div>
              </section>

              <section>
                <h3 className="font-serif text-lg text-moon-white mb-3">Key Findings</h3>
                <div className="space-y-3">
                  <div className="p-3 rounded-lg bg-cosmic-indigo/30 border border-gold-antique/10">
                    <p className="text-xs text-gold-antique uppercase tracking-wider mb-1">Ascendant</p>
                    <p className="text-sm text-moon-white">Capricorn — Practical, disciplined, ambitious nature</p>
                  </div>
                  <div className="p-3 rounded-lg bg-cosmic-indigo/30 border border-gold-antique/10">
                    <p className="text-xs text-gold-antique uppercase tracking-wider mb-1">Moon Sign</p>
                    <p className="text-sm text-moon-white">Taurus — Emotional stability, appreciation for beauty and comfort</p>
                  </div>
                  <div className="p-3 rounded-lg bg-cosmic-indigo/30 border border-gold-antique/10">
                    <p className="text-xs text-gold-antique uppercase tracking-wider mb-1">Current Dasha</p>
                    <p className="text-sm text-moon-white">Jupiter Mahadasha (2015-2032) — Period of growth and wisdom</p>
                  </div>
                </div>
              </section>

              <section>
                <h3 className="font-serif text-lg text-moon-white mb-3">AI Interpretation</h3>
                <p className="text-sm text-lavender/70 leading-relaxed">
                  With Jupiter as your current Mahadasha lord and positioned in the 10th house, this period emphasizes career growth and public recognition. Saturn's antardasha suggests disciplined effort will yield results after initial delays. The Gajakesari Yoga in your chart indicates strong intuitive abilities and potential for leadership roles.
                </p>
              </section>

              <div className="pt-6 border-t border-gold-antique/10 text-center">
                <p className="text-xs text-lavender/40">
                  This report is generated by AstraVeda 3D AI and is intended for reflection and entertainment.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
