export default function DisclaimerPage() {
  return (
    <main className="min-h-screen pt-20 pb-12">
      <div className="section-padding max-w-3xl mx-auto">
        <h1 className="heading-section mb-6">Astrology Disclaimer</h1>
        <div className="space-y-6 text-lavender/70 leading-relaxed">
          <div className="p-4 rounded-lg bg-status-warning/5 border border-status-warning/20">
            <p className="text-sm text-status-warning font-medium">Important Notice</p>
          </div>

          <p>AstraVeda 3D provides traditional Vedic astrology and palmistry guidance for reflection and entertainment purposes only. By using this platform, you acknowledge and agree to the following:</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">Not Professional Advice</h2>
          <p>The information provided on this platform, including birth chart interpretations, palm readings, and AI-generated responses, is not a substitute for professional medical, financial, legal, or psychological advice.</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">No Guaranteed Predictions</h2>
          <p>We do not claim 100% accuracy in predictions. Astrology is a traditional guidance system that reflects possibilities and tendencies, not certainties. Individual effort, choices, and circumstances play the primary role in life outcomes.</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">No Medical Diagnosis</h2>
          <p>Our platform does not provide medical diagnoses. For health concerns, always consult qualified healthcare professionals.</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">Optional Remedies</h2>
          <p>Any remedies or suggestions provided are entirely optional and traditional in nature. They are not compulsory and should not replace professional treatment or advice.</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">Palmistry Limitations</h2>
          <p>Palm scan interpretations are based on traditional palmistry beliefs and are intended for reflection and entertainment. We never claim exact predictions about death dates, accidents, or guaranteed wealth from palm features.</p>

          <h2 className="font-serif text-xl text-moon-white mt-8 mb-3">AI-Generated Content</h2>
          <p>Responses from Astra AI are generated by artificial intelligence and interpreted from calculated astrological data. The AI does not invent planetary positions but interprets supplied chart data.</p>

          <p className="text-sm text-lavender/50 mt-8">Last updated: 20 August 2026</p>
        </div>
      </div>
    </main>
  )
}
